---

- name: run command
  command: bash -lc "{{ cmd }}" chdir="{{ project_path }}"
  remote_user: "{{ deployer }}"
  environment:
    MIX_ENV: "{{ mix_env }}"
  register: cmd_output

- debug: msg="{{ cmd_output.stdout_lines }}"
