---
- name: "install asdf"
  git: repo="https://github.com/HashNuke/asdf.git" dest="~/.asdf" update=yes
  become: yes
  become_user: "{{deployer}}"


- name: "source asdf in bashrc"
  lineinfile: dest="~/.bash_profile" create=yes line="source ~/.asdf/asdf.sh"
  become: yes
  become_user: "{{deployer}}"


- name: "add asdf plugins"
  command: "bash -lc 'asdf plugin-add {{item}} https://github.com/HashNuke/asdf-{{item}}.git'"
  with_items:
    - nodejs
    - erlang
    - elixir
  become: yes
  become_user: "{{deployer}}"
